name: "Get workflow origin"
description: "Get PR number and target branch from pull_request or workflow_run"

outputs:
  pr_number:
    description: "Pull request number"
  target_branch:
    description: "Target (base) branch"

runs:
  using: "composite"
  steps:
    - id: compute
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
      with:
        script: |
          const event = context.payload;

          let pullRequestNumber = null;
          let targetBranch = null;

          if (event.pull_request) {
            prNumber = event.pull_request.number;
            targetBranch = event.pull_request.base.ref;
          }
          else if (event.workflow_run) {
            const run_id = event.workflow_run.id;

            // Find PR linked to the workflow run
            const prs = await github.rest.actions.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            if (prs.data.length > 0) {
              const pr = prs.data[0];
              pullRequestNumber = pr.number;
              targetBranch = pr.base.ref;
            }
          }

          core.setOutput("pr_number", pullRequestNumber);
          core.setOutput("target_branch", targetBranch);
